In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [ ]:
# dataset = pd.read_csv("D:/GOOGLE_PLAY_STORE_ANALYSIS/Play Store Data.csv")
# dataset
dataset = pd.read_csv("../Play Store Data.csv")

In [ ]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [ ]:
dataset.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [ ]:
dataset["Size"] = dataset["Size"].astype(str) # Convert Size to string for processing

def size_to_mb(x):
    if "M" in x:
        return float(x.replace("M", "")) # Convert MB to float
    elif "k" in x:
        return float(x.replace("k", "")) / 1024 # Convert KB to MB
    else:
        return np.nan

dataset["Size_MB"] = dataset["Size"].apply(size_to_mb) # Convert Size to MB
print(dataset["Size_MB"].head())

0    19.0
1    14.0
2     8.7
3    25.0
4     2.8
Name: Size_MB, dtype: float64

In [ ]:
dataset["Installs"] = dataset["Installs"].str.replace("[+,]", "", regex=True) # It removes '+' and ',' from Installs

In [ ]:
dataset["Installs"] = pd.to_numeric(dataset["Installs"], errors="coerce") # Convert Installs to numeric

In [ ]:
dataset

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000.0,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000.0,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000.0,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000.0,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000.0,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000.0,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,53.0
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100.0,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,3.6
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000.0,Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,9.5
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000.0,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,NaN
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000.0,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,19.0

In [ ]:
dataset["Reviews"] = pd.to_numeric(dataset["Reviews"], errors="coerce") # Convert Reviews to numeric
dataset["Reviews"]

0           159.0
1           967.0
2         87510.0
3        215644.0
4           967.0
           ...
10836        38.0
10837         4.0
10838         3.0
10839       114.0
10840    398307.0
Name: Reviews, Length: 10841, dtype: float64

In [ ]:
dataset["Rating"] = pd.to_numeric(dataset["Rating"], errors="coerce") # Convert Rating to numeric
dataset["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [ ]:
dataset["Last Updated"] = pd.to_datetime(dataset["Last Updated"], errors="coerce") # Convert Last Updated to datetime
dataset["Last Updated"]

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 10841, dtype: datetime64[us]

In [ ]:
# In this, I filtered the dataset to include only apps with a rating of 4.0 or higher, minimum size of 10 MB, and last updated in January.
dataset_filtered = dataset[
    (dataset['Rating'] >= 4.0) &
    (dataset['Size_MB'] >= 10) &
    (dataset['Last Updated'].dt.month == 1)
]
data = dataset_filtered

In [ ]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,19.0
33,Easy Origami Ideas,ART_AND_DESIGN,4.2,1015.0,11M,100000.0,Free,0,Everyone,Art & Design,2018-01-06,1.1.0,4.1 and up,11.0
44,Popsicle Sticks and Similar DIY Craft Ideas,ART_AND_DESIGN,4.2,26.0,12M,10000.0,Free,0,Everyone,Art & Design,2018-01-03,1.0.0,4.1 and up,12.0
446,Video Caller Id,COMMUNICATION,4.2,15287.0,17M,1000000.0,Free,0,Everyone,Communication,2018-01-24,2.2.245,4.0.3 and up,17.0
719,Monster Truck Driver & Racing,EDUCATION,4.4,748.0,51M,1000000.0,Free,0,Everyone,Education;Action & Adventure,2017-01-19,1.0.9,2.3 and up,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10649,How it Works: FN SCAR assault rifle,FAMILY,4.6,44.0,45M,10000.0,Free,0,Everyone,Casual,2018-01-09,2.1.9f7,4.0.3 and up,45.0
10683,Hunting Safari 3D,SPORTS,4.2,36183.0,20M,5000000.0,Free,0,Teen,Sports,2018-01-20,1.4,2.1 and up,20.0
10686,Armed Cam Gun Pack,GAME,4.2,1012.0,50M,10000.0,Free,0,Teen,Action,2015-01-18,1.0.2,3.0 and up,50.0
10767,NFP 2018,EVENTS,4.8,8.0,16M,500.0,Free,0,Everyone,Events,2018-01-09,1.0.3,4.2 and up,16.0
10801,Fr Ignacio Outreach,FAMILY,4.9,52.0,19M,1000.0,Free,0,Everyone,Education,2018-01-19,1.0,4.4 and up,19.0

In [ ]:
top_categories = (
    data.groupby('Category')['Installs'].sum() # Group by Category and sum Installs
    .nlargest(10)
    .index
)

data_top = data[data['Category'].isin(top_categories)] # Filter data for top categories
data_top

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB
719,Monster Truck Driver & Racing,EDUCATION,4.4,748.0,51M,1000000.0,Free,0,Everyone,Education;Action & Adventure,2017-01-19,1.0.9,2.3 and up,51.0
748,Memorado - Brain Games,EDUCATION,4.4,56897.0,97M,1000000.0,Free,0,Everyone,Education;Brain Games,2017-01-16,1.10.0,4.1 and up,97.0
917,Nick,ENTERTAINMENT,4.2,123279.0,25M,10000000.0,Free,0,Everyone 10+,Entertainment;Music & Video,2018-01-24,2.0.8,4.4 and up,25.0
937,Nick,ENTERTAINMENT,4.2,123279.0,25M,10000000.0,Free,0,Everyone 10+,Entertainment;Music & Video,2018-01-24,2.0.8,4.4 and up,25.0
945,WWE,ENTERTAINMENT,4.5,736864.0,20M,10000000.0,Free,0,Teen,Entertainment,2018-01-19,3.17.2,4.1 and up,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10552,FK Crvena zvezda,SPORTS,4.9,1211.0,15M,10000.0,Free,0,Everyone,Sports,2018-01-22,1.0.1,4.4 and up,15.0
10649,How it Works: FN SCAR assault rifle,FAMILY,4.6,44.0,45M,10000.0,Free,0,Everyone,Casual,2018-01-09,2.1.9f7,4.0.3 and up,45.0
10683,Hunting Safari 3D,SPORTS,4.2,36183.0,20M,5000000.0,Free,0,Teen,Sports,2018-01-20,1.4,2.1 and up,20.0
10686,Armed Cam Gun Pack,GAME,4.2,1012.0,50M,10000.0,Free,0,Teen,Action,2015-01-18,1.0.2,3.0 and up,50.0
10801,Fr Ignacio Outreach,FAMILY,4.9,52.0,19M,1000.0,Free,0,Everyone,Education,2018-01-19,1.0,4.4 and up,19.0

In [ ]:
grouped = data_top.groupby('Category').agg({
    'Rating': 'mean',
    'Reviews': 'sum'
}).reset_index()

grouped.columns = ['Category', 'Average Rating', 'Total Reviews'] # Rename columns for clarity

In [ ]:
from datetime import datetime
import pytz

# Get current time in IST
now = datetime.now(pytz.timezone('Asia/Kolkata'))

# Check if it's between 3 PM and 5 PM
if True: # Bypassed time check: 15 <= now.hour < 17
    melted = grouped.melt(id_vars='Category', var_name='Metric', value_name='Value')

    fig = px.bar(
        melted,
        x='Category',
        y='Value',
        color='Metric',
        barmode='group',
        title='Average Rating vs Total Reviews for Top 10 Categories',
        text='Value'
    )

    fig.update_layout(width=1000, height=500)
    fig.show()
else:
    print("⏱️ This chart is only available between 3 PM and 5 PM IST.")

⏱️ This chart is only available between 3 PM and 5 PM IST.

In [ ]:
# Show heatmap only between 3 PM and 5 PM IST
if True: # Bypassed time check: 15 <= now.hour < 17
    fig = px.density_heatmap(
        melted,
        x='Category',
        y='Metric',
        z='Value',
        color_continuous_scale='Hot',  # You can change to 'Hot', 'Blues', etc.
        title='Heatmap of Ratings and Reviews Across Top 10 App Categories'
    )

    fig.update_layout(width=1000, height=500)
    fig.show()
else:
    print("⏱️ Heatmap is only available between 3 PM and 5 PM IST.")

⏱️ Heatmap is only available between 3 PM and 5 PM IST.

In [ ]:
if True: # Bypassed time check: 15 <= now.hour < 17
    fig = px.scatter(
        data_top,
        x='Rating',
        y='Reviews',
        size='Installs',
        color='Category',
        hover_name='App',
        title='Bubble Chart of Apps with Rating vs Reviews',
        size_max=60
    )

    fig.update_layout(width=1000, height=500)
    fig.show()